### ISSUE TITLE
No Pom.xml in perspective folder

### ISSUE THREAD

**Issue by drevilmd** [inductiveautomation/ignition-sdk-examples#73]

**Comment by PerryAJ** [comment]
There won't be a pom in the perspective project, as it doesn't use Maven.  We've used Gradle internally for a while now, which is what the perspective example uses as well, in order to have the flexibility and integration of the nodejs requirements in a 'single tool'.  If you prefer maven, you could certainly use it to build perspective modules, but it would be up to you to set that up.  

The perspective example has a Readme with info and usage details.
